POST http://localhost:9090/urls HTTP/1.1
content-type: application/json

{
    "original_url": "http://test.com",
    "expires_at": "2006-01-03",
    "alias": "test"
}

###

GET http://localhost:9090/urls/1 HTTP/1.1