env: 'local'

http_server:
  addres: "localhost:8082"

storage:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  db_name: "url_shortener"
  ssl_mode: "disable"

cache:
  host: "localhost"
  port: 6379
  db: 0